#version 460

layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(rg16f, binding = 0) uniform image2D imgOutput;

layout(location = 1) uniform double t;

void main() {
    vec4 value = vec4(0.0, 0.0, 0.0, 1.0);
    ivec2 texelCoord = ivec2(gl_GlobalInvocationID.xy);
	
    value.x = sin(float(texelCoord.x)/(gl_NumWorkGroups.x) + float(4 * t));
    value.y = cos(float(texelCoord.y)/(gl_NumWorkGroups.y) + float(4 * t));
	
    imageStore(imgOutput, texelCoord, value);
}